# Generated by Django 5.0 on 2024-03-08 05:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('play', '0003_admin'),
    ]

    operations = [
        migrations.CreateModel(
            name='verify',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
            ],
            options={
                'db_table': 'verify',
            },
        ),
    ]
