# Generated by Django 5.0 on 2024-03-08 05:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('play', '0004_verify'),
    ]

    operations = [
        migrations.AddField(
            model_name='verify',
            name='pwd',
            field=models.CharField(default=1, max_length=15),
            preserve_default=False,
        ),
    ]
