# Generated by Django 5.0.1 on 2024-03-25 18:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('play', '0006_audiofile_kksongs_rockfile_usersongs'),
    ]

    operations = [
        migrations.CreateModel(
            name='event',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ename', models.CharField(max_length=50, null=True)),
                ('eurl', models.ImageField(null=True, upload_to='')),
                ('etitle', models.CharField(max_length=100, null=True)),
                ('elink', models.CharField(max_length=100, null=True)),
                ('eplace', models.CharField(max_length=100, null=True)),
                ('eprice', models.CharField(max_length=100, null=True)),
                ('elocation', models.CharField(max_length=100, null=True)),
                ('etiming', models.CharField(max_length=100, null=True)),
            ],
            options={
                'db_table': 'event',
            },
        ),
        migrations.DeleteModel(
            name='kksongs',
        ),
        migrations.DeleteModel(
            name='rockfile',
        ),
    ]
