# Generated by Django 5.0.1 on 2024-03-25 21:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('play', '0007_event_delete_kksongs_delete_rockfile'),
    ]

    operations = [
        migrations.DeleteModel(
            name='event',
        ),
    ]
